name: Deploy Bulletin Builder Api

on:
  push:
    branches: [ "stage" ]
    tags:
    - 'v*'


permissions:
  contents: read

jobs:

# ------- START Api PROCCESS -------- #

  TestApi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create environment and install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pip install pytest
          pip install -e .
          pip install mongomock

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '8.0'
          mongodb-db: 'test_db'
          mongodb-username: 'test_user'
          mongodb-password: 'test_password'

      - name: Run Tests with pytest
        env:
          DATABASE_URI: "mongodb://test_user:test_password@localhost:27017/test_db"
        run: |
          source env/bin/activate
          PYTHONPATH=$PYTHONPATH:./src pytest tests/

# ------- END Api PROCCESS -------- #    

# ------- START MERGE PROCCESS -------- #

  MergeMainApi:
    needs: [TestApi]
    name: Merge Stage with Main
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge stage -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: main
          github_token: ${{ github.token }}

# ------- END MERGE PROCCESS -------- #

# ------- START RELEASE PROCCESS -------- #

  PostRelease:
    needs: MergeMainApi
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    # API Zip
    - name: Zip artifact for deployment
      run: zip releaseApi.zip ./src/* -r
    # Upload Artifacts
    - name: Upload Api artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: Api
        path: releaseApi.zip
    # Generate Tagname
    - name: Generate Tagname for release
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES : stage,main
        BRANCH_HISTORY: last
    # Create release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
        release_name: Release ${{ steps.taggerDryRun.outputs.new_tag }}
        #body_path: ./body.md
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
    # Upload Assets to release
    - name: Upload Release Asset Api
      id: upload-Api-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./releaseApi.zip
        asset_name: releaseApi.zip
        asset_content_type: application/zip
    # update version pyproject.toml
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Update version in pyproject.toml
      run: |
        pip install toml
        python -c "import toml; f = open('pyproject.toml', 'r'); data = toml.load(f); f.close(); data['project']['version'] = '${{ steps.taggerDryRun.outputs.new_tag }}'; f = open('pyproject.toml', 'w'); toml.dump(data, f); f.close()"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update version to ${{ steps.taggerDryRun.outputs.new_tag }}"

# ------- END RELEASE PROCCESS -------- #